import type { Metadata } from "next";
import Link from "next/link";
import { Scale, ShieldAlert, FileText, Ban, AlertTriangle, Building2, CheckCircle2 } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | ZenScout AI by Aneevarp Solutions",
  description: "Statutory Terms of Service and User Agreement for ZenScout AI by Aneevarp Solutions under the Information Technology Act 2000, IT Rules 2021, and Indian Contract Act 1872.",
  alternates: {
    canonical: "/terms",
  }
};

export default function TermsOfService() {
  return (
    <div className="max-w-4xl mx-auto py-8 px-2 md:px-4">
      {/* Header */}
      <div className="mb-8">
        <div className="inline-flex items-center gap-1.5 bg-[#476550]/10 dark:bg-teal-900/30 text-[#476550] dark:text-[#A2BCA8] text-xs font-black px-3.5 py-1.5 rounded-full mb-3">
          <Scale className="w-4 h-4 text-[#476550] dark:text-[#A2BCA8]" />
          <span>STATUTORY USER AGREEMENT & LEGAL TERMS</span>
        </div>
        <h1 className="text-3xl md:text-5xl font-extrabold text-[#1A1F1F] dark:text-white tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-xs text-[#596060] dark:text-slate-400 font-bold">
          Last Updated & Effective Date: August 24, 2026 | Governing Law: India (Hyderabad Jurisdiction)
        </p>
      </div>
      
      <div className="space-y-6 text-[#596060] dark:text-[#CBD5E1] text-sm md:text-base leading-relaxed">
        
        {/* 1. Legal Agreement & Electronic Record */}
        <section className="bg-white dark:bg-[#222828] p-6 md:p-8 rounded-3xl border border-[#D8E2DA] dark:border-[#2D3636] shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-[#476550] dark:text-[#A2BCA8] font-bold text-lg">
            <FileText className="w-5 h-5" />
            <h2>1. Legal Agreement & Electronic Record Under IT Act 2000</h2>
          </div>
          <p>
            This document is an electronic record generated by a computer system and does not require physical or digital signatures. It is published in accordance with the provisions of <strong>Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021</strong> that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of <strong>ZenScout AI</strong> (a digital software product engineered by <strong>Aneevarp Solutions</strong>).
          </p>
          <p>
            By accessing, registering, or subscribing to ZenScout AI, you acknowledge that you are at least 18 years of age (or possess valid parental/guardian consent) and agree to be bound by these Terms and our Privacy Policy.
          </p>
        </section>

        {/* 2. Prohibited Content & User Rules */}
        <section className="bg-white dark:bg-[#222828] p-6 md:p-8 rounded-3xl border border-[#D8E2DA] dark:border-[#2D3636] shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-[#476550] dark:text-[#A2BCA8] font-bold text-lg">
            <Ban className="w-5 h-5" />
            <h2>2. Mandatory User Rules & Prohibition of Unlawful Content (Rule 3(1)(b))</h2>
          </div>
          <p>
            Pursuant to Rule 3(1)(b) of the IT Intermediary Rules 2021 / 2023, you explicitly agree not to upload, transmit, share, or generate any content through ZenScout AI that:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-xs">
            <li>Belongs to another person without authorization or infringes any patent, trademark, copyright, or proprietary rights.</li>
            <li>Is defamatory, obscene, pornographic, pedophilic, invasive of another's privacy, insulting or harassing on the basis of gender, racially or ethnically objectionable, or promotes money laundering or gambling.</li>
            <li>Deceives or misleads the addressee about the origin of the message or intentionally communicates misinformation.</li>
            <li>Threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order.</li>
            <li>Contains software viruses, Trojan horses, worm scripts, prompt injection attacks, or code designed to disrupt, limit, or damage computer software or hardware.</li>
          </ul>
        </section>

        {/* 3. Scope of Service & Intellectual Property */}
        <section className="bg-white dark:bg-[#222828] p-6 md:p-8 rounded-3xl border border-[#D8E2DA] dark:border-[#2D3636] shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-[#476550] dark:text-[#A2BCA8] font-bold text-lg">
            <Building2 className="w-5 h-5" />
            <h2>3. Intellectual Property Rights & Licensing</h2>
          </div>
          <p>
            All multi-agent pipelines, user interface code, visual styles, branding, trade dress, algorithms, and documentation relating to ZenScout AI and ZenResume are the exclusive intellectual property of <strong>Aneevarp Solutions</strong>.
          </p>
          <p className="text-xs">
            Users retain full ownership of their personal resumes, uploaded career history, and generated cover letters. Aneevarp Solutions claims no ownership over user-submitted career materials.
          </p>
        </section>

        {/* 4. Consumer Protection (E-Commerce) Rules 2020 & Pricing */}
        <section className="bg-white dark:bg-[#222828] p-6 md:p-8 rounded-3xl border border-[#D8E2DA] dark:border-[#2D3636] shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-[#476550] dark:text-[#A2BCA8] font-bold text-lg">
            <CheckCircle2 className="w-5 h-5" />
            <h2>4. Subscriptions, Pricing & Consumer Protection Disclosures</h2>
          </div>
          <p className="text-xs">
            In compliance with the <strong>Consumer Protection (E-Commerce) Rules, 2020</strong> and the <strong>Guidelines for Prevention and Regulation of Dark Patterns, 2023</strong>:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-xs">
            <li><strong>Transparent Pricing:</strong> All subscription rates (₹299 for 1-Month, ₹699 for 3-Month, ₹1,999 for Annual Pro) are stated transparently without hidden recurring surcharges or surprise billing.</li>
            <li><strong>Zero Dark Patterns:</strong> We do not employ fake urgency timers, forced bundled purchases, deceptive subscription renewals, or pre-ticked opt-in checkboxes.</li>
            <li><strong>Refund Policy:</strong> Due to the immediate delivery of unlimited AI compute and digital career acceleration tools, subscription fees are non-refundable except where required by applicable statutory consumer protection laws.</li>
          </ul>
        </section>

        {/* 5. Limitation of Liability */}
        <section className="bg-white dark:bg-[#222828] p-6 md:p-8 rounded-3xl border border-[#D8E2DA] dark:border-[#2D3636] shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-[#476550] dark:text-[#A2BCA8] font-bold text-lg">
            <AlertTriangle className="w-5 h-5" />
            <h2>5. Disclaimer of Employment Warranties & Limitation of Liability</h2>
          </div>
          <p className="text-xs">
            ZenScout AI provides AI-assisted recruitment tools, resume scoring, and mock interview coaching. While designed to enhance candidate competitiveness, <strong>Aneevarp Solutions does not act as an employment agency and makes no warranty or guarantee of job offers, callback rates, or interview selections from third-party employers</strong>.
          </p>
        </section>

        {/* 6. Governing Law & Dispute Resolution */}
        <section className="bg-emerald-50/40 dark:bg-emerald-950/20 p-6 md:p-8 rounded-3xl border-2 border-[#476550]/30 dark:border-[#A2BCA8]/30 shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-[#476550] dark:text-[#A2BCA8] font-extrabold text-lg">
            <Scale className="w-5 h-5" />
            <h2>6. Governing Law & Exclusive Territorial Jurisdiction</h2>
          </div>
          <p className="text-xs">
            These Terms shall be governed by, interpreted, and construed in accordance with the laws of <strong>India</strong>. The courts located in <strong>Hyderabad, Telangana, India</strong> shall have exclusive territorial jurisdiction over any legal disputes, claims, or arbitration proceedings arising under this agreement.
          </p>
          <div className="p-4 bg-white dark:bg-[#222828] rounded-2xl border border-slate-200 dark:border-slate-800 text-xs">
            <strong>Grievance & Legal Notice Desk:</strong><br />
            Attn: Grievance Officer, Aneevarp Solutions<br />
            Email: <a href="mailto:aneevarpsolutions@gmail.com" className="text-[#476550] dark:text-[#A2BCA8] underline font-bold">aneevarpsolutions@gmail.com</a><br />
            Address: Hyderabad, Telangana - 500081, India
          </div>
        </section>

      </div>
    </div>
  );
}
